const Discord = require("discord.js");
const client = new Discord.Client();
const config = require("./config.json");

client.once('ready', () => {
	console.log('Ready!');
});

client.on('message', message => {
	if (message.content.startsWith(config.prefix + "bb1")) {
		message.channel.send('`You direct Jonah\'s attention to the punch bowl.  "What a tender thing," you observe.  "He certainly seems out of place here."`\n\n`"Ahh," Jonah says knowingly, with an uncharacteristically soft smile, "my Barnabas.  Yes, he is something of a lamb amidst the wolves tonight."  Jonah nudges you playfully.  "Perhaps you could be his shepherd."`\n\n`You tilt your head to conceal your pleased smile behind your glass of champagne, but you know Jonah sees it.  You are watching the pretty blush that is rising from under Barnabas\'s collar.  "Soft as a lamb, I see."`\n\n`"Come on," Jonah says, gentler now, "he could use a kind sort to make him feel more welcome."  He walks you over and introduces you, and it would be impossible for you to miss how Barnabas beams like sunshine the second he sees Jonah.  Jonah kisses his cheek, and whispers in his ear with a touch to his face before leaving him with you.`\n`Barnabas glances down, peering up at you from beneath long light lashes.  "Thank you, truly, for coming to talk to me," he says.  "Jonah does not always keep the friendliest company."`\n\n`At the other end of the long table where you stand, a dark and brooding gentleman is scowling into his drink.  He is exceptionally handsome, yet appears just as uncomfortable as Barnabas with most present company.`\n\n`* Select` :a: `to ask Barnabas what he knows about these strange people.`\n`* Select` :b: `to get the gossip from Barnabas about the hot guy.`');

	} else if (message.content.startsWith(config.prefix + "bb2")) {
	  message.channel.send('`"Yes," you say, "so I\'ve noticed."  You lower your voice.  "Barnabas, just what kind of party is this, anyway?"`\n\n`Barnabas frowns in thought.  "I do not pretend to understand the extent of Jonah\'s work," he admits, "but the monstrous men you see before you share his interest in the fantastical and terrible."  Barnabas steps closer to you.  "My friend," he says helplessly, "if I could sacrifice myself to save Jonah, I would--for I worry about the state of his soul, and I wager most of those here have sold theirs already."`\n\n`You shudder at the implication.`\n\n`Barnabas looks up then, and smiles.  "Although," he says, brightening back up a little, "speaking of wagers ... this gentleman walking toward us now has always been amicable to me, at least inasmuch as he enjoys a good game."`\n\n`You follow Barnabas\'s line of sight, and feel a sense of dread wash over you when you see Mordechai Lukas returning and heading your way.`\n\n`* Select` :a: `to plead with Barnabas to make no wagers with Mordechai.`\n`* Select` :b: `to watch ...`');

	} else if (message.content.startsWith(config.prefix + "bb3")) {
		message.channel.send('`Before you can reconsider, you grab Barnabas by the hand and race out to the hall with him.  He lets out a little squeak but offers no resistance, and in your impassioned state you all but slam him up against a wall.`\n\n`"What are you--," he starts to say.`\n\n`"You stay away from that man!!" you shout, your noses almost touching.  "I don\'t know what he is, but he is dangerous and I will *not* see you get killed!"`\n\n`Barnabas makes a bewildered little sound, you can feel the warm breath on your lips, and next thing you know your mouths are crashed together.  He tastes like spun sugar and iron, and you think your knees might give out when he moans softly into your mouth.  You feel him hardening against your hip, and you jam your thigh between his legs to let him rut while you work your way down his throat, leaving possessive purple bruises in your wake.`\n\n`This is how Jonah finds you.`\n\n`* Select` :a: `to beg Jonah for forgiveness.`\n`* Select` :b: `to invite Jonah to join you.`');

	} else if (message.content.startsWith(config.prefix + "bb4")) {
		message.channel.send('`Mordechai approaches, and before you can say a word, he looks at you sneeringly and says, "Don\'t you worry about earlier.  Jonah has already instructed me that you are not for me."`\n\n`"Greetings, Mordechai," says Barnabas.  "I was wondering if I could interest you in a little gamble again tonight."`\n\n`While Mordechai and Barnabas chat, you feel a pair of arms twine about your waist, and you spin in sudden surprise to find Jonah embracing you.  It is shockingly intimate, the two of you drawn so close that your hips meet, and he places his hands on either side of your face.  "Lovely," he says quietly.  "I knew you were for me."`\n\n`"I don\'t understand," you mutter, your heart pounding.`\n\n`"Oh, I believe you do," he says.  "What do you think will happen to our sweet little lamb there, making bets with monsters?"`\n\n`"I\'m not sure," you admit.  "Something bad."`\n\n`"Almost certainly," Jonah says crisply.  "But you don\'t know what."  He pauses, brushing your hair off your forehead.  "Is that why you made no move to try and stop it?"`\n\n`You swallow.  There\'s no denying what you\'ve done.  You nod.  "I needed to know," you mumble.`\n\n`Jonah kisses you on the forehead.  "And that is nothing to be ashamed of," he says, pinning you in place with the sheer force behind his green eyes.  "You\'ve made a distinct impression on me, my dear," he murmurs.  "I\'ve been developing a theory, one which would require me to take a partner at my Institute."  He pauses.  "Come learn what it truly means to need to know," he implores softly.  "Be my head archivist.  I am not sure yet what all that entails, but together we could live forever."`\n\n`* Select` :a: `to serve The Eye (and Jonah).`\n`* Select` :b: `to politely decline.`');

	} else if (message.content.startsWith(config.prefix + "bb5")) {
		message.channel.send('`Jonah laughs richly.  "Don\'t be silly," he says, "this is the loveliest thing I\'ve gotten to watch all night.  Please, continue."`\n\n`"Wh-what?" you stutter.`\n\n`Jonah sinks into the plush couch across from you.  You tremble, wondering if this is some kind of trick and he isn\'t about to accost you, or worse.`\n\n`Evidently not, because Barnabas gently touches your cheek and turns your head back to face him like this is perfectly normal.  Perhaps it is, for them.  He licks the seam of your mouth hungrily, and you stroke up and down Barnabas\'s flanks as Jonah speaks.  "You have no idea what our new friend has done for you tonight," he tells Barnabas.  "You must return the favor."`\n\n`"Anything you say," Barnabas whines.`\n\n`"I know," says Jonah darkly.  "I think I\'d like to watch you get your mouth used."`\n\n`Barnabas wastes no time in going down on you, and you\'re certainly not stopping him.  He is beyond talented, attentive and enthusiastic for the smell and taste of you.  You twist his ponytail around your wrist as you fuck into his mouth, and when you look up, Jonah\'s eyes are not on your sex but forcing intense contact with your own gaze.  You feel witnessed.  You feel holy.  You feel Known.`\n\n`==========THE END==========`\n`Congratulations!`\n`* You saved Barnabas Bennett from The Lonely`\n`* You got head from Barnabas Bennett`\n`* Jonah Magnus Watched you erotically`\n`Great Job!`');

	} else if (message.content.startsWith(config.prefix + "bb6")) {
		message.channel.send('`Jonah sinks into the plush couch across from you and pats the cushion next to his, and Barnabas and you waste not a moment in each straddling one of Jonah\'s thighs.  He spreads his legs to make room for you both, chuckling darkly as he wraps his arms tightly around your waists.`\n\n`You whimper as you rub your heat up and down his fine trousers.  Jonah kisses your temple, making shushing sounds into your hair.  "We have all the time in the world," he promises, then ducks his head to catch Barnabas\'s mouth with his.`\n\n`Jonah slides his tongue between your lips next, and you moan around it.  "I need," you say when he pulls back, "I need ..."`\n\n`"I know," Jonah purrs, "and you\'re going to get it."`\n\n`You never would have pegged (no pun intended) Barnabas for a top, but you scarcely see it coming when the two of them flip the script and drag you using your hair onto your back.  They position you perfectly for Barnabas to thrust inside you, clenched fingers grinding the bones of your ankles, while you gag on Jonah\'s cock too far down your throat.`\n\n`This is the start of a beautiful arrangement, and it is not long before the three of you more or less share the estate.  Jonah and Barnabas keep you collared and rarely clothed, and you do not mind at all.`\n\n`There are worse fates than ending up the pampered sex pet of a handsome intellectual Regency monster and his dandy husband.`\n\n`==========THE END==========`\n`Congratulations!`\n`* You saved Barnabas Bennett from The Lonely`\n`* You got double-teamed by Barnabas Bennett and Jonah Magnus`\n`* You moved into the Magnus Estate as Jonah and Barnabas\'s sex slave`\n`Great Job!`');

}
});

client.login(config.token);
